version: '3'
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"

  db:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: MY_DATABASE
      MYSQL_USER: fethi
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"
